import java.lang.Exception


fun main(args: Array<String>) {


    val dog = Dog()
    dog.eat()

    val cat = Cat()
    cat.eat()

}










